### ISSUE TITLE
Error with lst but not with lst()

### ISSUE THREAD

**Issue by zarniak** [zarniak/exercism.io#19]
@virtuallight 
test are ok but only if i change code in test script - all "lst" to "lst()" - why so? is this property thing messing thing up?
for example in this line: https://github.com/zarniak/exercism.io/blob/2c2d4565441f7e7174594dea8e91ce6dfabbef38/allergies/allergies_test.py#L36
or here https://github.com/zarniak/exercism.io/blob/2c2d4565441f7e7174594dea8e91ce6dfabbef38/allergies/allergies_test.py#L39
or here
https://github.com/zarniak/exercism.io/blob/2c2d4565441f7e7174594dea8e91ce6dfabbef38/allergies/allergies_test.py#L45

the error i get is:

```
E.EFFFEE.E.F.
======================================================================
ERROR: test_allergic_to_eggs_and_peanuts (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 48, in test_allergic_to_eggs_and_peanuts
    self.assertCountEqual(Allergies(3).lst, ['eggs', 'peanuts'])
  File "/usr/lib/python3.4/unittest/case.py", line 1129, in assertCountEqual
    first_seq, second_seq = list(first), list(second)
TypeError: 'method' object is not iterable

======================================================================
ERROR: test_allergic_to_everything (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 62, in test_allergic_to_everything
    'chocolate', 'pollen', 'cats'
  File "/usr/lib/python3.4/unittest/case.py", line 1129, in assertCountEqual
    first_seq, second_seq = list(first), list(second)
TypeError: 'method' object is not iterable

======================================================================
ERROR: test_allergic_to_lots_of_stuff (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 56, in test_allergic_to_lots_of_stuff
    ['strawberries', 'tomatoes', 'chocolate', 'pollen', 'cats'])
  File "/usr/lib/python3.4/unittest/case.py", line 1129, in assertCountEqual
    first_seq, second_seq = list(first), list(second)
TypeError: 'method' object is not iterable

======================================================================
ERROR: test_allergic_to_more_than_eggs_but_not_peanuts (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 51, in test_allergic_to_more_than_eggs_but_not_peanuts
    self.assertCountEqual(Allergies(5).lst, ['eggs', 'shellfish'])
  File "/usr/lib/python3.4/unittest/case.py", line 1129, in assertCountEqual
    first_seq, second_seq = list(first), list(second)
TypeError: 'method' object is not iterable

======================================================================
ERROR: test_ignore_non_allergen_score_parts (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 69, in test_ignore_non_allergen_score_parts
    'pollen', 'cats'
  File "/usr/lib/python3.4/unittest/case.py", line 1129, in assertCountEqual
    first_seq, second_seq = list(first), list(second)
TypeError: 'method' object is not iterable

======================================================================
FAIL: test_allergic_to_just_eggs (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 39, in test_allergic_to_just_eggs
    self.assertEqual(Allergies(1).lst, ['eggs'])
AssertionError: <bound method Allergies.lst of <allergies.Allergies object at 0x7f4fb92ab860>> != ['eggs']

======================================================================
FAIL: test_allergic_to_just_peanuts (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 42, in test_allergic_to_just_peanuts
    self.assertEqual(Allergies(2).lst, ['peanuts'])
AssertionError: <bound method Allergies.lst of <allergies.Allergies object at 0x7f4fb92ab550>> != ['peanuts']

======================================================================
FAIL: test_allergic_to_just_strawberries (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 45, in test_allergic_to_just_strawberries
    self.assertEqual(Allergies(8).lst, ['strawberries'])
AssertionError: <bound method Allergies.lst of <allergies.Allergies object at 0x7f4fb92ab7f0>> != ['strawberries']

======================================================================
FAIL: test_no_allergies_at_all (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 36, in test_no_allergies_at_all
    self.assertEqual(Allergies(0).lst, [])
AssertionError: <bound method Allergies.lst of <allergies.Allergies object at 0x7f4fb92ab6a0>> != []

----------------------------------------------------------------------
Ran 13 tests in 0.032s

FAILED (failures=4, errors=5)


```

**Comment by virtuallight** [comment]
@zarniak I don't think that you should be touching the tests as they are the indication if your code is written correctly. Lets rather look what to change in https://github.com/zarniak/exercism.io/blob/master/allergies/allergies.py.

Removing `@property` (or commenting out as you did) in https://github.com/zarniak/exercism.io/blob/2c2d4565441f7e7174594dea8e91ce6dfabbef38/allergies/allergies.py#L19 is fine. I'd make `lst` a property but Exercism expects a method there. Not sure why - maybe they just didn't want to add this somewhat "advanced" idea of property decorators 🤷‍♂️

So once you remove the `@property` decorator then you need to call the method always as `self.lst()`. That's just the syntax for it. Even if you don't pass any arguments. So the line https://github.com/zarniak/exercism.io/blob/2c2d4565441f7e7174594dea8e91ce6dfabbef38/allergies/allergies.py#L17 needs updating. 

This will also fix https://github.com/zarniak/exercism.io/issues/18. The error there is:
```
    return item in self.allergen_list
TypeError: argument of type 'method' is not iterable
```
It's a bit convoluted what's happening. If your're interested read ahead - but that's not really that crucial when starting with Python.
So, `item in self.allergen_list` works only if `self.allergen_list` is an object which can hold other objects  ("iterable" in Python's lingo) i.e `self.allergen_list` is e.g. a list or dictionary. In our case:
https://github.com/zarniak/exercism.io/blob/2c2d4565441f7e7174594dea8e91ce6dfabbef38/allergies/allergies.py#L17. But here is the problem. By omitting the `()` after `lst` you don't point to the *result* of method `lst` but you point to the *method* itself. That's why `TypeError: argument of type 'method' is not iterable`. That would still work if you'd keep `@property` decorator as then https://github.com/zarniak/exercism.io/blob/2c2d4565441f7e7174594dea8e91ce6dfabbef38/allergies/allergies.py#L17 would already point to the *result* and `item in self.allergen_list` would execute without issues. But we're getting rid of the decorator :)

**Comment by virtuallight** [comment]
https://github.com/zarniak/exercism.io/issues/19#issuecomment-453620062 will also fix https://github.com/zarniak/exercism.io/issues/18. The error there is:
```
    return item in self.allergen_list
TypeError: argument of type 'method' is not iterable
```
It's a bit convoluted what's happening. If you're interested then read ahead - but that's not really that crucial when starting with Python.

So, `item in self.allergen_list` works only if `self.allergen_list` is an object which can hold other objects  ("iterable" in Python's lingo) i.e `self.allergen_list` is e.g. a list or dictionary. In our case:
https://github.com/zarniak/exercism.io/blob/2c2d4565441f7e7174594dea8e91ce6dfabbef38/allergies/allergies.py#L17. But here is the problem. By omitting the `()` after `lst` you don't point to the *result* of the method `lst` but you point to the *method* itself. That's why `TypeError: argument of type 'method' is not iterable`. That would still work if you'd keep `@property` decorator as then https://github.com/zarniak/exercism.io/blob/2c2d4565441f7e7174594dea8e91ce6dfabbef38/allergies/allergies.py#L17 would already point to the *result* and `item in self.allergen_list` would execute without issues. But we're getting rid of the decorator :)
